feat: implement keynote page
pycontw/pycontw-2021 pull request #78
Opened 2021-06-25 23:33 UTC by mattwang44

## Types of Changes

- [ ] **Bugfix**
- [x] **New feature**
- [ ] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [ ] **Other (please describe)**

## Description

Add keynote page (`<host>/<base>/<lang>/conference/keynotes`).

## More Information

https://user-images.githubusercontent.com/24987826/123493898-95917e00-d650-11eb-8949-cecc88ac1d42.mp4

2021-06-26 18:27 UTC, flynnhou requested changes

2021-06-26 18:27 UTC, flynnhou commented on components/core/tabs/Tabs.vue
> +    @apply border-2 rounded-t-lg bg-transparent cursor-pointer;
```suggestion
    @apply border rounded-t-lg bg-transparent cursor-pointer;
```

to align with the design

2021-06-26 18:27 UTC, flynnhou commented on components/core/tabs/Tabs.vue
> +    @apply inline-block text-sm rounded-2xl min-w-full;
```suggestion
    @apply inline-block text-sm rounded-2xl min-w-full border-2;
```

to align with the design.

2021-06-26 18:27 UTC, flynnhou commented on components/core/tabs/Tabs.vue
> +    padding: 20px;
add the following css rule to align with the design:

```css
    box-shadow: 6px 6px 0 #c2a53a;
```

copied from @dabingnai's event card styling - https://github.com/dabingnai/pycontw-2021/blob/55d21044107cd6af9925f536ee1150874ba91b53/components/events/EventCard.vue#L41

2021-06-26 18:37 UTC, flynnhou commented on components/core/tabs/Tabs.vue
> +    computed: {},
remove unused line

2021-06-26 18:37 UTC, flynnhou commented on components/core/tabs/Tabs.vue
> +        },
Love the implementation! Elegant!

2021-06-27 04:57 UTC, mattwang44 commented on pages/conference/keynotes.vue
> +        }))
Directly use `$makeId()` in the loop results in error.

![image](https://user-images.githubusercontent.com/24987826/123533327-f8654100-d746-11eb-82dc-857481263f9e.png)

2021-06-27 05:03 UTC, mattwang44 commented
@flynnhou Thanks for reviewing!
Added a new commit e27b09d for `head()`.

2021-06-27 06:24 UTC, flynnhou approved these changes
lgtm

2021-06-27 06:24 UTC, merged