style(footer): fix footer based on design spec
pycontw/pycontw-2021 pull request #87
Opened 2021-07-01 02:45 UTC by linooohon

## Types of Changes

- [x] **Bugfix**
- [ ] **New feature**
- [ ] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [ ] **Other (please describe)**

## Description

Fixed #73

2021-07-04 17:45 UTC, josix requested changes

2021-07-04 17:48 UTC, josix commented
Hello @linooohon, thanks for your hard work. There are two coding style nit and others LGTM.

2021-07-06 00:51 UTC, linooohon commented
Hi @josix, thanks for your review. Here is the commit for this fix! [fded3f4](https://github.com/pycontw/pycontw-2021/pull/87/commits/fded3f49f43b47dfc6df9229b00d391a98ed0fe6)

2021-07-06 16:03 UTC, josix requested changes

2021-07-07 01:14 UTC, linooohon commented on components/core/footer/FooterIcon.vue
> +                :alt="`${icon.src.split('/')[3].split('.')[0]} Footer Icon`"
Thanks for your advice, I agree with your point. [17f24fb](https://github.com/pycontw/pycontw-2021/pull/87/commits/17f24fb306945cfca234985482b17d37ba60c36b)

2021-07-07 06:55 UTC, josix approved these changes
LGTM, thank you @linooohon!

2021-07-07 06:58 UTC, merged